# This script is made to remove all resources on Azure.
# It deletes the Cosmos DB database and the resource group
# Generated by ChatGPT or based on official docs
# https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-resource-group

from azure.identity import DefaultAzureCredential
from azure.mgmt.cosmosdb import CosmosDBManagementClient
from azure.mgmt.resource import SubscriptionClient
from azure.mgmt.resource import ResourceManagementClient


def get_subscription_id():
    # Authenticate using DefaultAzureCredential (works with `az login`)
    credential = DefaultAzureCredential()
    subscription_client = SubscriptionClient(credential)

    # Get list of subscriptions and print the first (default) one
    subscription = next(subscription_client.subscriptions.list())
    subscription_id = subscription.subscription_id
    return subscription_id


# Set your values
subscription_id = get_subscription_id()
resource_group_name = "groupd-chatbot-deploy"
account_name = "groupdchatbotdb1234"

credential = DefaultAzureCredential()
client = CosmosDBManagementClient(credential, subscription_id)

delete_operation = client.database_accounts.begin_delete(
    resource_group_name, account_name)

delete_operation.result()

print(f"Cosmos DB account '{account_name}' deleted successfully.")

resource_client = ResourceManagementClient(credential, subscription_id)
delete_async_operation = resource_client.resource_groups.begin_delete(
    resource_group_name)

# Wait for completion
delete_async_operation.result()

print(f"Resource group '{resource_group_name}' deleted successfully.")
