# This script is made to remove all resources on Azure.
# It deletes the Cosmos DB database and the resource group
# Generated by ChatGPT or based on official docs
# https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-resource-group

import configparser
from azure.identity import DefaultAzureCredential
from azure.mgmt.cosmosdb import CosmosDBManagementClient
from azure.mgmt.resource import SubscriptionClient
from azure.mgmt.resource import ResourceManagementClient


def get_subscription_id():
    # Authenticate using DefaultAzureCredential (works with `az login`)
    credential = DefaultAzureCredential()
    subscription_client = SubscriptionClient(credential)

    # Get list of subscriptions and print the first (default) one
    subscription = next(subscription_client.subscriptions.list())
    subscription_id = subscription.subscription_id
    return subscription_id


# Set your values
def load_config():
    config = configparser.ConfigParser()
    config.read('config.ini')
    return config


config = load_config()

REGION = config.get('azure', 'region')
SUBSCRIPTION_ID = get_subscription_id()
ACCOUNT_NAME = config.get('azure', 'account_name')
RESOURCE_GROUP_NAME = config.get('azure', 'resource_group_name')

credential = DefaultAzureCredential()
client = CosmosDBManagementClient(credential, SUBSCRIPTION_ID)

delete_operation = client.database_accounts.begin_delete(
    RESOURCE_GROUP_NAME, ACCOUNT_NAME)

delete_operation.result()

print(f"Cosmos DB account '{ACCOUNT_NAME}' deleted successfully.")

resource_client = ResourceManagementClient(credential, SUBSCRIPTION_ID)
delete_async_operation = resource_client.resource_groups.begin_delete(
    RESOURCE_GROUP_NAME)

# Wait for completion
delete_async_operation.result()

print(f"Resource group '{RESOURCE_GROUP_NAME}' deleted successfully.")
