# This script is made to setup all resources on Azure.
# First it needs to create a new resource group
# then it creates a vector Cosmos DB database with EnableNoSQLVectorSearch capability enabled
# Generated by ChatGPT or based on official docs
# https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-resource-group

from azure.identity import DefaultAzureCredential
from azure.mgmt.cosmosdb import CosmosDBManagementClient
from azure.mgmt.cosmosdb.models import Capability
from azure.mgmt.resource import SubscriptionClient
from azure.mgmt.resource import ResourceManagementClient

from azure.mgmt.cosmosdb.models import (
    DatabaseAccountCreateUpdateParameters,
    Location,
    ConsistencyPolicy,
)


def get_subscription_id():
    # Authenticate using DefaultAzureCredential (works with `az login`)
    credential = DefaultAzureCredential()
    subscription_client = SubscriptionClient(credential)

    # Get list of subscriptions and print the first (default) one
    subscription = next(subscription_client.subscriptions.list())
    subscription_id = subscription.subscription_id
    return subscription_id


def create_resource_group(name, location):
    # Obtain the management object for resources.
    credential = DefaultAzureCredential()
    resource_client = ResourceManagementClient(credential, subscription_id)

    # Provision the resource group.
    rg_result = resource_client.resource_groups.create_or_update(
        name, {"location": location}
    )

    print(f"Provisioned resource group {rg_result.name}")
    return rg_result.name


# Replace with your details
location = "switzerlandnorth"  # the region
subscription_id = get_subscription_id()
resource_group_name = create_resource_group("groupd-chatbot-deploy", location)
account_name = "groupdchatbotd1234"

# # Authenticate
#
# # Define the capability to be added
# capability = Capability(name="EnableNoSQLVectorSearch")
#
# # Update the Cosmos DB account
# update_params = DatabaseAccountUpdateParameters(capabilities=[capability])
#
# async_update = client.database_accounts.begin_update(
#     resource_group_name, account_name, update_params
# )


def create_cosmos_db():

    # Capabilities list (including Vector Search)
    capabilities = [Capability(name="EnableNoSQLVectorSearch")]

    # Create the Cosmos DB account
    create_params = DatabaseAccountCreateUpdateParameters(
        location=location,
        locations=[Location(location_name=location)],
        kind="GlobalDocumentDB",
        capabilities=capabilities,
        consistency_policy=ConsistencyPolicy(
            default_consistency_level="Session"),
        database_account_offer_type="Standard",
    )

    credential = DefaultAzureCredential()
    client = CosmosDBManagementClient(credential, subscription_id)
    async_create = client.database_accounts.begin_create_or_update(
        resource_group_name, account_name, create_params
    )

    result = async_create.result()
    print(f"Created Cosmos DB account: {result.name}")


create_cosmos_db()
